cln: make Dup3 platform independent
ElementsProject/peerswap pull request #176
Opened 2023-03-09 11:39 UTC by JssDWt

Dup3 is not available on Mac. Use the sys/unix package for a platform independent version.

2023-03-12 14:35 UTC, nepet approved these changes
I have no idea if this is gona conflict with other unix/linux distributions but it seems to work for me on jammy and OsX 13.2.1.

2023-03-12 18:04 UTC, grubles commented
Will this break aarch64? See #89

2023-03-12 18:31 UTC, nepet commented
Thanks @grubles, this seems to be more complicated than I thought. We can set OS dependent build constraints https://pkg.go.dev/cmd/go#hdr-Build_constraints to at least support `aarch64` and `x86_64` linux and darwin systems. Does anyone have a better solution to capture panic logs?

2023-03-12 18:35 UTC, nepet requested changes
We need to use OS dependent build constraints https://pkg.go.dev/cmd/go#hdr-Build_constraints as `aarch64` systems apperently only support `dup3`. See #89.

2023-03-12 18:37 UTC, grubles commented
It actually appears to build fine on my aarch64 Debian 11 machine.

2023-03-12 18:53 UTC, nepet commented
@grubles Thanks for testing. It looks like Raspiblitz is using ubuntu 18.04 (based on debian 10) for its base, as far as I can tell from their repository. According to https://github.com/ngaut/log/issues/4 this still is an ongoing issue.
I guess it is best to decide on the OS via build constraints (freebsd is also possible) to decide between dup2/dup3

2023-03-13 12:16 UTC, JssDWt commented
The Dup2 in the golang.org/x/sys/unix package appears to contain a platform independent version of Dup2/Dup3. Look at the source [here](https://cs.opensource.google/go/x/sys/+/refs/tags/v0.6.0:unix/syscall_linux.go;l=1817), in the left lane you see there's a separate syscall file for most (all?) platforms there.

2023-03-13 12:49 UTC, nepet approved these changes
> The Dup2 in the golang.org/x/sys/unix package I used appears to contain a platform independent version of Dup2/Dup3. Look at the source [here](https://cs.opensource.google/go/x/sys/+/refs/tags/v0.6.0:unix/syscall_linux.go;l=1817), in the left lane you see there's a separate syscall file for most (all?) platforms there. So on linux Dup2 actually calls Dup3 under the hood, but not on darwin, and so forth.

Oh, you are right! The golang.org/x/sys/uinx package is doing already exactly what we proposed. Thanks for pointing this out, so there is no need to change anything and we can merge.

2023-03-13 15:30 UTC, grubles commented
ACK.

2023-03-16 11:44 UTC, JssDWt commented
rebased

2023-04-28 11:34 UTC, nepet commented
Sorry to bother you but could you rebase again? We can merge it now since the ugly config pr was merged.

2023-04-28 14:23 UTC, JssDWt commented
@nepet rebased

2023-05-02 13:37 UTC, merged