Test for basic recovery
ElementsProject/peerswap pull request #97
Opened 2022-07-11 13:31 UTC by nepet

This pull request addresses some issues where the recovery of a swap (in csv condition) failed with a panic. It adds the following:
 - A basic test for recovery
 - Wait for the node to be in sync with the blockchain before attempting to recover
 - Add some helper functions to the test framework
 - Fixes an issue with the transaction watcher having to wait an extra confirmation

2022-07-11 17:15 UTC, nepet commented
To be clear, This pr does not fix the panic we could not reproduce but it encountered some problems that also came up when discussing #73.

2022-07-13 19:48 UTC, wtogami requested changes

2022-07-13 19:48 UTC, wtogami commented on cmd/peerswap-plugin/main.go
> +	}, 10*time.Second, 10*time.Minute)
```
2022-07-13T16:54:45.513Z INFO    plugin-peerswap-plugin: PeerSwap Initialized, running PeerSwap commit 95eac6a5281fb3cfbae549222ebd1aa29485f0b4
2022-07-13T16:54:45.555Z INFO    plugin-peerswap-plugin: Waiting for cln to be synced
2022-07-13T17:04:48.800Z INFO    plugin-peerswap-plugin: Killing plugin: exited during normal operation
```

We found 10 minutes can be too short. Perhaps it should wait forever? It is CLN's problem to let us know when it thinks it is ready.

2022-07-17 19:10 UTC, wtogami commented
> Wait for the node to be in sync with the blockchain before attempting to recover

This improved things a bit but it but we need more startup checks. PeerSwap gives up too quickly sending things into cancel when it should have seen it is temporary.

For now this is good enough for merge. Want to squash fixups first?

2022-07-17 19:10 UTC, wtogami approved these changes

2022-07-17 20:09 UTC, nepet commented
Yes, let me squash that fixups!

2022-07-17 22:46 UTC, nepet commented
Squashed the fixups and rebased this ugly pr onto master.

2022-07-17 23:10 UTC, wtogami commented
ACK 688ebca and tested for several days by a few people 
confirmed 6135d8d is equivalent

2022-07-17 23:11 UTC, merged